# -*- coding: utf-8 -*-
"""FIFA Project - 2026 World Cup Predictor

Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/10MH6YlRuzkCB7Z5gFWwwosTpaPNOc4mb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import seaborn as sns
import statsmodels.api as sm
import scipy.stats as stats
from collections import defaultdict

from google.colab import files
uploaded = files.upload()

results = pd.read_csv("results.csv")
fixtures = pd.read_csv("wc_2026_fixtures.csv")
teams = pd.read_csv("wc_2026_teams.csv")
elo = pd.read_csv("elo_ratings_wc2026.csv")

print(results.shape)
print(results['date'].min(), results['date'].max())

# =============================================================================
# STAGE 1 — ELO RATING ENGINE
# =============================================================================

"""## Elo Rating Update Equations

**Step 1 — Expected probability of home team winning:**

$$P_{home} = \frac{1}{1 + 10^{(R_{away} - R_{home})/400}}$$

**Step 2 — Actual result:**

$$W = \begin{cases} 1 & \text{home win} \\ 0.5 & \text{draw} \\ 0 & \text{away win} \end{cases}$$

**Step 3 — Rating update:**

$$R_{home}^{new} = R_{home} + K \times (W - P_{home})$$

$$R_{away}^{new} = R_{away} + K \times ((1 - W) - (1 - P_{home}))$$
"""

def update_elo(home_rating, away_rating, home_score, away_score, k=40):
    expected_home = 1 / (1 + 10**((away_rating - home_rating)/400))
    if home_score > away_score:
        actual_home = 1
    elif home_score == away_score:
        actual_home = 0.5
    else:
        actual_home = 0
    new_home_rating = home_rating + k*(actual_home - expected_home)
    new_away_rating = away_rating - k*(actual_home - expected_home)
    return new_home_rating, new_away_rating


def calculate_elo_ratings(df, k=40, initial_rating=1000):
    ratings = {}
    records = []
    df = df.sort_values('date')

    for _, row in df.iterrows():
        home = row['home_team']
        away = row['away_team']

        if home not in ratings:
            ratings[home] = initial_rating
        if away not in ratings:
            ratings[away] = initial_rating

        home_rating = ratings[home]
        away_rating = ratings[away]

        # record elo BEFORE updating — avoids data leakage
        records.append({
            'home_team': home,
            'away_team': away,
            'home_elo': home_rating,
            'away_elo': away_rating,
            'home_score': row['home_score'],
            'away_score': row['away_score'],
            'neutral': row['neutral']
        })

        new_home, new_away = update_elo(home_rating, away_rating, row['home_score'], row['away_score'])
        ratings[home] = new_home
        ratings[away] = new_away

    return ratings, pd.DataFrame(records)


ratings, match_df = calculate_elo_ratings(results)

elo_df = pd.DataFrame.from_dict(ratings, orient='index', columns=['elo_rating'])
elo_df = elo_df.sort_values('elo_rating', ascending=False)
print(elo_df.head(20))

# =============================================================================
# STAGE 2 — POISSON REGRESSION MATCH MODEL
# =============================================================================

# filter to World Cup matches only
wc_matches = match_df[results['tournament'] == 'FIFA World Cup']
wc_matches = wc_matches.dropna(subset=['home_score', 'away_score'])

X = wc_matches[['home_elo', 'away_elo', 'neutral']].copy()
X['neutral'] = X['neutral'].astype(int)
X = sm.add_constant(X)

y_home = wc_matches['home_score']
y_away = wc_matches['away_score']

home_model = sm.GLM(y_home, X, family=sm.families.Poisson()).fit()
away_model = sm.GLM(y_away, X, family=sm.families.Poisson()).fit()

print(home_model.summary())
print(away_model.summary())


def simulate_match(home_elo, away_elo, neutral=1):
    """Simulate a single match. Returns (home_goals, away_goals)."""
    match_input = pd.DataFrame({
        'const': [1],
        'home_elo': [home_elo],
        'away_elo': [away_elo],
        'neutral': [neutral]
    })
    lambda_home = home_model.predict(match_input)[0]
    lambda_away = away_model.predict(match_input)[0]
    home_goals = stats.poisson.rvs(lambda_home)
    away_goals = stats.poisson.rvs(lambda_away)
    return home_goals, away_goals


def simulate_match_winner(team1, team2):
    """Simulate a match and return the winner. Handles penalties on draw."""
    elo1 = ratings.get(team1, 1000)
    elo2 = ratings.get(team2, 1000)
    g1, g2 = simulate_match(elo1, elo2, neutral=1)
    if g1 > g2:
        return team1
    elif g2 > g1:
        return team2
    else:
        # draw — decide on penalties (50/50 with slight elo bias)
        elo_diff = elo1 - elo2
        p_team1_wins_pens = 1 / (1 + 10**(-elo_diff / 400))
        return team1 if np.random.random() < p_team1_wins_pens else team2

# =============================================================================
# STAGE 3 — GROUP STAGE SIMULATOR
# =============================================================================

def simulate_group_stage(fixtures, ratings):
    """Simulate all group stage matches. Returns points table."""
    group_results = {}
    group_matches = fixtures[fixtures['stage'] == 'Group Stage']

    for _, match in group_matches.iterrows():
        team1 = match['team1']
        team2 = match['team2']
        elo1 = ratings.get(team1, 1000)
        elo2 = ratings.get(team2, 1000)
        goals1, goals2 = simulate_match(elo1, elo2, neutral=1)

        if team1 not in group_results:
            group_results[team1] = {'points': 0, 'gd': 0, 'group': match['group']}
        if team2 not in group_results:
            group_results[team2] = {'points': 0, 'gd': 0, 'group': match['group']}

        # goal difference as tiebreaker
        group_results[team1]['gd'] += goals1 - goals2
        group_results[team2]['gd'] += goals2 - goals1

        if goals1 > goals2:
            group_results[team1]['points'] += 3
        elif goals1 == goals2:
            group_results[team1]['points'] += 1
            group_results[team2]['points'] += 1
        else:
            group_results[team2]['points'] += 3

    return group_results


def get_group_qualifiers(group_results):
    """Return top 2 teams from each group, sorted by points then goal difference."""
    df = pd.DataFrame(group_results).T
    df['points'] = df['points'].astype(int)
    df['gd'] = df['gd'].astype(int)

    qualifiers = {}
    for group in df['group'].unique():
        if pd.isna(group):
            continue
        group_teams = df[df['group'] == group].sort_values(
            ['points', 'gd'], ascending=[False, False]
        )
        qualifiers[group] = list(group_teams.index[:2])
    return qualifiers

# =============================================================================
# STAGE 4 — KNOCKOUT STAGE SIMULATOR
# The 2026 World Cup has a Round of 32, Round of 16, QF, SF, Final
# Group winners/runners-up are seeded into the bracket per FIFA rules
# =============================================================================

def simulate_knockout_round(teams_list):
    """Simulate one knockout round. Takes list of teams, returns list of winners."""
    winners = []
    for i in range(0, len(teams_list), 2):
        if i + 1 < len(teams_list):
            winner = simulate_match_winner(teams_list[i], teams_list[i+1])
            winners.append(winner)
        else:
            winners.append(teams_list[i])
    return winners


def build_r32_bracket(qualifiers):
    """
    Build the Round of 32 bracket from group qualifiers.
    2026 format: 12 groups (A-L), top 2 from each = 24 teams + 8 best third-place = 32 total.
    We simplify by taking top 2 from each group and seeding by group winner/runner-up.
    """
    # winners = positions [0], runners-up = positions [1]
    groups = sorted(qualifiers.keys())
    winners   = [qualifiers[g][0] for g in groups if len(qualifiers[g]) > 0]
    runners_up = [qualifiers[g][1] for g in groups if len(qualifiers[g]) > 1]

    # interleave: W1 vs RU2, W2 vs RU1 style pairing (simplified)
    bracket = []
    for i in range(len(winners)):
        bracket.append(winners[i])
        if i < len(runners_up):
            # pair winner of group i against runner-up of next group
            bracket.append(runners_up[(i + 1) % len(runners_up)])

    return bracket


def simulate_full_tournament(fixtures, ratings):
    """Simulate a full tournament from group stage to final. Returns winner."""
    # group stage
    group_results = simulate_group_stage(fixtures, ratings)
    qualifiers = get_group_qualifiers(group_results)

    # build knockout bracket
    bracket = build_r32_bracket(qualifiers)

    # simulate knockout rounds until one team remains
    while len(bracket) > 1:
        bracket = simulate_knockout_round(bracket)

    return bracket[0]

# =============================================================================
# STAGE 5 — MONTE CARLO SIMULATION (100,000 runs)
# =============================================================================

def run_monte_carlo(fixtures, ratings, n_simulations=100000):
    """Run n_simulations full tournament simulations. Returns win probability dict."""
    win_counts = defaultdict(int)

    for i in range(n_simulations):
        if i % 10000 == 0:
            print(f"  Simulation {i:,} / {n_simulations:,}...")
        winner = simulate_full_tournament(fixtures, ratings)
        win_counts[winner] += 1

    # convert to probabilities
    win_probs = {team: count / n_simulations for team, count in win_counts.items()}
    return dict(sorted(win_probs.items(), key=lambda x: x[1], reverse=True))

print("\nRunning Monte Carlo simulation — this will take a few minutes...")
win_probs = run_monte_carlo(fixtures, ratings, n_simulations=100000)

# =============================================================================
# STAGE 6 — RESULTS & VISUALISATION
# =============================================================================

# print top 20 predictions
results_df = pd.DataFrame.from_dict(win_probs, orient='index', columns=['win_probability'])
results_df['win_probability_pct'] = results_df['win_probability'] * 100
print("\n=== 2026 FIFA WORLD CUP WIN PROBABILITIES ===")
print(results_df.head(20).to_string())

# bar chart — top 16 teams
top16 = results_df.head(16)

fig, ax = plt.subplots(figsize=(12, 7))
bars = ax.barh(
    top16.index[::-1],
    top16['win_probability_pct'][::-1],
    color='steelblue',
    edgecolor='white',
    linewidth=0.5
)

# add percentage labels
for bar, val in zip(bars, top16['win_probability_pct'][::-1]):
    ax.text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2,
            f'{val:.1f}%', va='center', fontsize=10)

ax.set_xlabel('Win Probability (%)', fontsize=12)
ax.set_title('2026 FIFA World Cup — Predicted Win Probabilities\n(100,000 Monte Carlo Simulations)', fontsize=13, fontweight='bold')
ax.set_xlim(0, top16['win_probability_pct'].max() * 1.2)
ax.xaxis.set_major_formatter(mtick.FormatStrFormatter('%.0f%%'))
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig('wc2026_predictions.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved as wc2026_predictions.png")
