# -*- coding: utf-8 -*-
"""FIFA Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10MH6YlRuzkCB7Z5gFWwwosTpaPNOc4mb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

results = pd.read_csv("results.csv")
fixtures = pd.read_csv("wc_2026_fixtures.csv")
teams = pd.read_csv("wc_2026_teams.csv")
elo = pd.read_csv("elo_ratings_wc2026.csv")

print(results.shape)
print(results['date'].min(), results['date'].max())

"""## Elo Rating Update Equations

**Step 1 — Expected probability of home team winning:**

$$P_{home} = \frac{1}{1 + 10^{(R_{away} - R_{home})/400}}$$

**Step 2 — Actual result:**

$$W = \begin{cases} 1 & \text{home win} \\ 0.5 & \text{draw} \\ 0 & \text{away win} \end{cases}$$

**Step 3 — Rating update:**

$$R_{home}^{new} = R_{home} + K \times (W - P_{home})$$

$$R_{away}^{new} = R_{away} + K \times ((1 - W) - (1 - P_{home}))$$
"""

def update_elo(home_rating, away_rating, home_score, away_score, k=40):
    expected_home = 1 / (1 + 10**((away_rating - home_rating)/400))
    if home_score > away_score:
        actual_home = 1
    elif home_score == away_score:
        actual_home = 0.5
    else:
        actual_home = 0
    new_home_rating = home_rating + k*(actual_home - expected_home)
    new_away_rating = away_rating - k*(actual_home - expected_home)
    return new_home_rating, new_away_rating

def calculate_elo_ratings(df, k=40, initial_rating=1000):

    # store each team's current rating
    ratings = {}

    # store a snapshot of every match for the feature matrix
    records = []

    # sort matches chronologically
    df = df.sort_values('date')

    # loop through every match
    for _, row in df.iterrows():

        home = row['home_team']
        away = row['away_team']

        # if we haven't seen a team before, give them the initial rating
        if home not in ratings:
            ratings[home] = initial_rating
        if away not in ratings:
            ratings[away] = initial_rating

        # get current ratings
        home_rating = ratings[home]
        away_rating = ratings[away]

        # record elo BEFORE updating to avoid data leakage
        records.append({
            'home_team': home,
            'away_team': away,
            'home_elo': home_rating,
            'away_elo': away_rating,
            'home_score': row['home_score'],
            'away_score': row['away_score'],
            'neutral': row['neutral']
        })

        # update ratings using your function from before
        new_home, new_away = update_elo(home_rating, away_rating, row['home_score'], row['away_score'])

        # store the updated ratings back in the dictionary
        ratings[home] = new_home
        ratings[away] = new_away

    return ratings, pd.DataFrame(records)

ratings, match_df = calculate_elo_ratings(results)

# convert to a sorted dataframe so we can read it easily
elo_df = pd.DataFrame.from_dict(ratings, orient='index', columns=['elo_rating'])
elo_df = elo_df.sort_values('elo_rating', ascending=False)
print(elo_df.head(20))

"""Data leakage could occur when using elo scores as the elo contains previous years performance"""

print(match_df.head())
print(match_df.shape)

# filter to World Cup matches only
wc_matches = match_df[results['tournament'] == 'FIFA World Cup']
print(wc_matches.shape)

print(wc_matches[['home_elo', 'away_elo', 'neutral', 'home_score', 'away_score']].isnull().sum())

wc_matches = wc_matches.dropna(subset=['home_score', 'away_score'])

import statsmodels.api as sm

# features
X = wc_matches[['home_elo', 'away_elo', 'neutral']].copy()
X['neutral'] = X['neutral'].astype(int)  # convert True/False to 1/0
X = sm.add_constant(X)  # adds the intercept term

# targets
y_home = wc_matches['home_score']
y_away = wc_matches['away_score']

# train two Poisson models
home_model = sm.GLM(y_home, X, family=sm.families.Poisson()).fit()
away_model = sm.GLM(y_away, X, family=sm.families.Poisson()).fit()

print(home_model.summary())

print(away_model.summary())

import scipy.stats as stats

def simulate_match(home_elo, away_elo, neutral=1):

    # build the feature input for the models
    match_input = pd.DataFrame({
        'const': [1],
        'home_elo': [home_elo],
        'away_elo': [away_elo],
        'neutral': [neutral]
    })

    # predict expected goals (lambda) for each team
    lambda_home = home_model.predict(match_input)[0]
    lambda_away = away_model.predict(match_input)[0]

    # sample a scoreline from two independent Poisson distributions
    home_goals = stats.poisson.rvs(lambda_home)
    away_goals = stats.poisson.rvs(lambda_away)

    return home_goals, away_goals

print(simulate_match(1473, 1380))

# check a few teams' current elo ratings
teams_to_check = ['France', 'Brazil', 'Argentina', 'England', 'Spain']
for team in teams_to_check:
    print(f"{team}: {ratings[team]:.1f}")

print(fixtures['team1'].unique())

# find teams in fixtures that don't have an elo rating
group_stage = fixtures[~fixtures['team1'].str.contains('1A|1B|1C|1D|1E|1F|1G|1H|1I|1J|1K|1L|R32|QF|SF|3rd|Best|Finalist', na=False)]

missing = [t for t in group_stage['team1'].unique() if t not in ratings]
print(missing)